name: Lint

on: [push, pull_request]

jobs:
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: psf/black@stable
      #  with:
      #    options: "--check --verbose"
      - name: Check permissions
        id: check-folder-permission
        #run: git update-index --chmod=+x entrypoint.sh
        run: ls -l

      - uses: sudonorm/format-with-black@v1.1
        with:
          src: "."
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          echo "changes made"